### ISSUE TITLE
TODO (Para fazer)

### ISSUE THREAD

**Issue by TiagoDanin** [SynkoDevelopers/EDPlugins#2]
# Funções de Suporte:
- [x] Inline
- [x] Padrão de mensagens para plugins de pesquisas
- [x] Processamento de mensagens para plugins de pesquisas
- [x] Plugin de ajuda (/help)
- [x] Processamento de erros
- [x] Autocomplete de textos (Usado dados da google) *Recomendado usar em inline*

# Novos plugins
- [x] 9GAG (Sem a API que fica caindo todo dia)
- [x] Google
- [ ] Legendas (Download e Pesquisa)
- [ ] Spotify
- [x] Coelhos (API: https://api.bunnies.io/v2/loop/random/?media=gif)

# Migração dos Plugins
- [x] Perguntas para o ED!
- [x] Dados
- [x] GIF
- [x] Latex/Sticker
- [ ] IMDb
- [ ] Google Maps
- [ ] Wikipedia
- [ ] Youtube Pesquisa
- [ ] Torrent pesquisar
- [ ] Google Cotaçãoo
- [x] Github
- [ ] Hora
- [ ] Check IP
- [x] XKCD

# Talvez (Baixa prioridade)
- [ ] Pokedex
- [ ] Clima
- [ ] Emoji
- [ ] Calculadora
- [ ] Instagram
- [ ] Fale
- [ ] Tradução
- [ ] Transito
